version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: KhaastNginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./website/static:/usr/share/nginx/html/website/static
      - ./website/media:/usr/share/nginx/html/website/media
      - ./nginx/khaast.ir.crt:/etc/ssl/certs/khaast.ir.crt
      - ./nginx/khaast.ir.key:/etc/ssl/private/khaast.ir.key
    ports:
      - "8001:80"
    depends_on:
      - website
    restart: always


  website:
    build:
      context: ./website
    entrypoint: /app/entrypoint.sh
    container_name: KhaastWebsite
    volumes:
      - ./website:/app
    restart: always