# Generated by Django 5.2.3 on 2025-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('a', 'عمومی'), ('b', 'اضطراری'), ('c', 'اخبار'), ('d', 'کمک نقدی'), ('e', 'نیاز به محل سکونت'), ('f', 'توسعه نرم افزار')], default='a', max_length=1),
        ),
    ]
